name: 'Comment Terraform Plan'
description: 'A cool Github Action to put easy-to-read comments for TF Plan'
inputs:
  plan:
    description: 'The path to the JSON File containing the Terraform Plan'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ github.action_path }}/requirements.txt

    - name: Run the action
      shell: bash
      run: |
        python ${{ github.action_path }}/src/main.py ${{ inputs.plan }}
